export enum SCENERIO_ONE {
	MIN_TOTAL_BUDGET = 0,
	MAX_TOTAL_BUDGET = 45,
	MIN_CARBON_EMISSIONS = 0,
	MAX_CARBON_EMISSIONS = 550,
	MUST_HAVE_WATER_PROOFING = 1,
	MUST_HAVE_DURABILITY_SURGE = 1,
	MUST_HAVE_ECO_BOOST = 0,
}

export enum SCENERIO_TWO {
	MIN_TOTAL_BUDGET = 0,
	MAX_TOTAL_BUDGET = 47,
	MIN_CARBON_EMISSIONS = 0,
	MAX_CARBON_EMISSIONS = 350,
	MUST_HAVE_ECO_BOOST = 1,
	MUST_HAVE_GREEN_BLEND = 1,
	MUST_HAVE_DURABILITY_SURGE = 0,
}

export enum SCENERIO_THREE {
	MIN_TOTAL_BUDGET = 0,
	MAX_TOTAL_BUDGET = 50,
	MIN_CARBON_EMISSIONS = 0,
	MAX_CARBON_EMISSIONS = 600,
	MUST_HAVE_SMART_STRENGTH_BLEND = 1,
	MUST_HAVE_ECO_BOOST = 0,
	MUST_HAVE_INDUSTRIAL_GRADE_BOOST = 1,
}

export enum SCENERIO_FOUR {
	MIN_TOTAL_BUDGET = 0,
	MAX_TOTAL_BUDGET = 40,
	MIN_CARBON_EMISSIONS = 0,
	MAX_CARBON_EMISSIONS = 550,
	MUST_HAVE_AFFORDABLE_MIX = 1,
	MUST_HAVE_ECO_BOOST = 0,
	MUST_HAVE_HOUSING_STRENGTH_BOOST = 1,
}

export enum SCENERIO_FIVE {
	MIN_TOTAL_BUDGET = 0,
	MAX_TOTAL_BUDGET = 40,
	MIN_CARBON_EMISSIONS = 0,
	MAX_CARBON_EMISSIONS = 550,
	MUST_HAVE_ECO_BOOST = 0,
	MUST_HAVE_SMART_STRENGTH_BLEND = 1,
	MUST_HAVE_WEATHER_SHIELD = 1,
}

export enum MULTIPLIER {
	COST = 1000000,
	CARBON_EMISSIONS = 1000, 
	INNOVATION = 500,
}